### ISSUE TITLE
Can I see conversations when I run test?

### ISSUE THREAD

**Issue by hunkim** [codeforequity-at/botium-connector-dialogflow#14]
```bash
13:39 $ botium-cli run --verbose


  0 passing (1ms)
```

give us rather simple results. May I see the conversations between botium and my dialogflow agent?

Or is there any way to use `botium-cli emulator`?

```
$ botium-cli emulator < my_exam_score.txt
```
is not pretty.

**Comment by ujja** [comment]
We dont support it yet. A terminal is not the right tool to display rich components.

But you can see it on Dialogflow Console.:

![image](https://user-images.githubusercontent.com/15360723/62105053-9e7d4780-b2a1-11e9-8cef-9b7c8cc2060c.png)

**Comment by codeforequity-at** [comment]
or you could use to mochawesome reporter to get an html report including
the conversation

ujja <notifications@github.com> schrieb am Di., 30. Juli 2019, 08:16:

**Comment by codeforequity-at** [comment]
Or you can use Botium Box ...
