### ISSUE TITLE
Dialogflow Connector doesn't work with V2 API

### ISSUE THREAD

**Issue by pakmingwCorp** [codeforequity-at/botium-connector-dialogflow#2]
The new Dialogflow V2 API requires the use of fulfillmentMessages instead of fulfillmentText.

https://dialogflow.com/docs/reference/v1-v2-migration-guide-fulfillment#fulfillment_messages_reference

I have confirmed this is the case with the Dialogflow engineering team, so we need to fix botium-connector-dialogflow/dist/botium-connector-dialogflow-cjs.js at line 215 onwards and botium-connector-dialogflow-es.js as well.

Regards, Pak

**Comment by pakmingwCorp** [comment]
Here's my fix:

      if (this$1.caps[Capabilities.DIALOGFLOW_USE_INTENT]) {
        if (response.queryResult.intent) {
          var botMsg = { sender: 'bot', sourceData: response.queryResult, messageText: response.queryResult.intent.displayName };
          this$1.queueBotSays(botMsg);
        }
      } else {
        console.debug('Detected bot response.');
        if (response.queryResult.fulfillmentText) {
          console.debug('Dialogflow V1 API response detected.');
          var botMsg$1 = { sender: 'bot', sourceData: response.queryResult, messageText: response.queryResult.fulfillmentText };
          this$1.queueBotSays(botMsg$1);
        } else {
          console.debug('Dialogflow V2 API response detected.');
          console.debug('Message: ' + JSON.stringify(response.queryResult.fulfillmentMessages));
          // iterate over messages
          response.queryResult.fulfillmentMessages.forEach(
            function(element) {
              console.debug('Iterating: ' + JSON.stringify(element));
              if (element.text) {
                console.debug('Text object: ' + JSON.stringify(element.text));
                var botMsg$1 = { sender: 'bot', sourceData: response.queryResult, messageText: element.text.text[0] };
                this$1.queueBotSays(botMsg$1);
              }
            });
        }
      }

**Comment by codeforequity-at** [comment]
Great fix - can you please make a pull request out of your code changes ? Thanks!

**Comment by pakmingwCorp** [comment]
Hi there,

OK, I had a quick look through the original package code (since my fix above just patches the dist/ code directly) and I think my patch is done -- but if possible I'd like to pass it through your usual testing / packaging pipeline to make sure it is at the right level of quality. Is this documented somewhere? Can you perhaps drop me a mail at pakmingw at google dot com so I can have a quick chat?

**Comment by codeforequity-at** [comment]
The pipeline is currently rather simple: when running "npm run build", the code style gets verified, this is part of the build. Will do a code review then.

**Comment by pakmingwCorp** [comment]
Hi there, I've prepared the code fix (plus tested it locally) on a local branch, but when I try to git push it up, it says I don't have rights (probably the case). Can you confirm?

```
 ~/../botium-connector/botium-connector-dialogflow/  ⑂ DialogflowV2APIfix +  >  git push origin DialogflowV2APIFix
ERROR: Permission to codeforequity-at/botium-connector-dialogflow.git denied to pakmingwCorp.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by pakmingwCorp** [comment]
Sorry -- I should add I've added my ssh keys etc. and I do have access to another GitHub repo, so I suspect this is not the problem. As you can probably tell I'm a little bit green on this, so please bear with me! :)

**Comment by codeforequity-at** [comment]
hello, easiest way is to just fork the repository, make the changes and open a pull request here

**Comment by pakmingwCorp** [comment]
Hi there, I've just created my pull request -- let me know what you think.

**Comment by codeforequity-at** [comment]
Thanks, I merged the pull request into an own feature branch now, from where to do some testing - maybe I will have to add a switch to support V1 and V2 of the API in parallel, as I think there are lots of people out there still using V1.
I think you have far more competence in Dialogflow than me - we have some open issues regarding the dialogflow connector, could you think about giving some input on them ?

**Comment by pakmingwCorp** [comment]
Re: Version switch, I think that's a really good idea. I also think that the V2 API may undergo some changes, so managing versions is a feature that makes sense.

If you do have some open issues, sure -- send them over to me and I can see if I can get our support / product team to comment on them to give us direction on this.

Thanks again for your help to guide me through this process and for contributing to this open source project!

**Comment by codeforequity-at** [comment]
The one issue where I really have no plan at all is this one:
https://github.com/codeforequity-at/botium-core/issues/88
It has to do with simulating account linking over the Dialogflow API.

And there are two easier ones:
https://github.com/codeforequity-at/botium-core/issues/118
Botium just has to be adapted to query provider specific responses.

https://github.com/codeforequity-at/botium-core/issues/78
This is maybe more an issue that I have never done anything with Actions On Google ...

**Comment by codeforequity-at** [comment]
Working with V2 by default, except when activated feature do require so.
